import asyncio
import json
import logging
import re
import os
import subprocess
import threading
from contextlib import suppress
from threading import Lock
from typing import Optional

import ctranslate2
import numpy as np
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from faster_whisper import WhisperModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("remote-transcriber")

MODEL_SIZE = os.getenv("WHISPER_MODEL", "large-v3")
DEVICE = os.getenv("WHISPER_DEVICE", "cuda")
COMPUTE_TYPE = os.getenv("WHISPER_COMPUTE", "float16")
MIN_SAMPLES = int(os.getenv("MIN_SAMPLES", str(16000)))
WINDOW_SAMPLES = int(os.getenv("WINDOW_SAMPLES", str(16000 * 6)))
TRANSCRIBE_INTERVAL = float(os.getenv("TRANSCRIBE_INTERVAL", "0.6"))
VAD_FILTER = os.getenv("VAD_FILTER", "false").lower() == "true"
ENGINE = os.getenv("STT_ENGINE", "auto").lower()

# Domain vocabulary prompt — primes the Whisper decoder to prefer these tokens.
# Override with WHISPER_PROMPT env var; set to "" to disable.
_DEFAULT_PROMPT = (
    "統計解析、構造方程式モデリング、潜在変数、観測変数、因子負荷量、パス係数、"
    "適合度、CFI、RMSEA、GFI、AGFI、SRMR、TLI、カイ二乗値、自由度、"
    "修正指数、期待パラメータ変化、多重共線性、"
    "平均、標準偏差、分散、歪度、尖度、標準化、"
    "帰無仮説、対立仮説、p値、有意水準、検出力、"
    "相関、回帰、因果関係、係数、内生変数、外生変数、"
    "母集団、標本、信頼区間、共分散、誤差項、測定モデル、構造モデル、"
    "石原先生、鈴木先生、寺尾先生、"
    "オールコネクト、福井ブローインズ、SMBC、"
    "経営技術革新工学コース、MOT"
)
_REPO_ROOT       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_AUTO_VOCAB_FILE = os.path.join(_REPO_ROOT, "context", "auto_vocab.txt")
_IMPROVE_SCRIPT  = os.path.join(_REPO_ROOT, "scripts", "idle_improve.py")

def _load_auto_vocab() -> str:
    """Return extra vocabulary from auto_vocab.txt (auto-generated by idle_improve.py)."""
    try:
        content = open(_AUTO_VOCAB_FILE).read().strip()
        if content:
            logger.info("Loaded %d chars of auto-vocab from %s", len(content), _AUTO_VOCAB_FILE)
        return content
    except FileNotFoundError:
        return ""

_extra_vocab = _load_auto_vocab()
_base_prompt  = os.getenv("WHISPER_PROMPT", _DEFAULT_PROMPT)
if _extra_vocab:
    _base_prompt = (_base_prompt or "") + ("、" if _base_prompt else "") + _extra_vocab
INITIAL_PROMPT: str | None = _base_prompt or None

VOSK_SCRIPT = os.getenv("VOSK_STREAM_SCRIPT", os.path.expanduser("~/voice/remote_stream_stt.py"))

# ---------------------------------------------------------------------------
# Idle-based self-improvement
# ---------------------------------------------------------------------------
AUTO_IMPROVE       = os.getenv("AUTO_IMPROVE", "true").lower() == "true"
IDLE_TRIGGER_SECS  = int(os.getenv("IDLE_TRIGGER_SECS", str(10 * 60)))  # 10 min

_active_sessions      = 0
_active_sessions_lock = Lock()
_idle_timer: threading.Timer | None = None


def _session_started() -> None:
    global _active_sessions, _idle_timer
    with _active_sessions_lock:
        _active_sessions += 1
        if _idle_timer is not None:
            _idle_timer.cancel()
            _idle_timer = None


def _session_ended() -> None:
    global _active_sessions, _idle_timer
    with _active_sessions_lock:
        _active_sessions = max(0, _active_sessions - 1)
        if _active_sessions == 0 and AUTO_IMPROVE and os.path.isfile(_IMPROVE_SCRIPT):
            _idle_timer = threading.Timer(IDLE_TRIGGER_SECS, _run_idle_improve)
            _idle_timer.daemon = True
            _idle_timer.start()
            logger.info("No active sessions — will run idle_improve.py in %ds", IDLE_TRIGGER_SECS)


def _run_idle_improve() -> None:
    venv_python = os.path.join(_REPO_ROOT, ".venv", "bin", "python3")
    python = venv_python if os.path.isfile(venv_python) else "python3"
    try:
        logger.info("Idle: launching %s", _IMPROVE_SCRIPT)
        subprocess.Popen(
            [python, _IMPROVE_SCRIPT],
            cwd=_REPO_ROOT,
            stdout=open("/tmp/idle_improve.log", "a"),
            stderr=subprocess.STDOUT,
        )
    except Exception as exc:
        logger.warning("idle_improve launch failed: %s", exc)

app = FastAPI(title="Remote Whisper Server")


def resolve_engine() -> str:
    if ENGINE in {"vosk", "whisper"}:
        return ENGINE
    if os.path.isfile(VOSK_SCRIPT):
        return "vosk"
    return "whisper"


ACTIVE_ENGINE = resolve_engine()


def resolve_runtime() -> tuple[str, str]:
    # Use GPU-first defaults, but avoid hard failure if CUDA is missing.
    device = DEVICE
    compute = COMPUTE_TYPE
    if device == "cuda":
        try:
            if ctranslate2.get_cuda_device_count() == 0:
                logger.warning("CUDA requested but not available; falling back to CPU int8")
                return "cpu", "int8"
        except Exception:
            logger.warning("Could not detect CUDA devices; falling back to CPU int8")
            return "cpu", "int8"
    return device, compute


RUNTIME_DEVICE, RUNTIME_COMPUTE = resolve_runtime()
model: WhisperModel | None = None
model_lock = Lock()


def _run_warmup(test_model: WhisperModel) -> None:
    # Run a tiny inference to catch missing CUDA runtime libs early.
    warmup_audio = np.zeros(16000, dtype=np.float32)
    segments, _ = test_model.transcribe(
        warmup_audio,
        language="en",
        beam_size=1,
        best_of=1,
        vad_filter=False,
        condition_on_previous_text=False,
        without_timestamps=True,
        temperature=0.0,
    )
    # Force eager execution to surface backend errors now.
    _ = list(segments)


def _load_model(device: str, compute_type: str) -> WhisperModel:
    loaded = WhisperModel(MODEL_SIZE, device=device, compute_type=compute_type)
    _run_warmup(loaded)
    return loaded


def _is_cuda_runtime_error(exc: Exception) -> bool:
    msg = str(exc).lower()
    needles = ["libcublas", "libcudnn", "cuda", "cublas", "cannot be loaded"]
    return any(n in msg for n in needles)


def ensure_model() -> None:
    global model, RUNTIME_DEVICE, RUNTIME_COMPUTE
    with model_lock:
        if model is not None:
            return
        try:
            model = _load_model(RUNTIME_DEVICE, RUNTIME_COMPUTE)
        except Exception as exc:
            if RUNTIME_DEVICE == "cuda" and _is_cuda_runtime_error(exc):
                logger.warning("CUDA runtime unavailable, falling back to CPU int8: %s", exc)
                RUNTIME_DEVICE, RUNTIME_COMPUTE = "cpu", "int8"
                model = _load_model(RUNTIME_DEVICE, RUNTIME_COMPUTE)
            else:
                raise


def force_cpu_fallback() -> None:
    global model, RUNTIME_DEVICE, RUNTIME_COMPUTE
    with model_lock:
        RUNTIME_DEVICE, RUNTIME_COMPUTE = "cpu", "int8"
        model = _load_model(RUNTIME_DEVICE, RUNTIME_COMPUTE)


if ACTIVE_ENGINE == "whisper":
    ensure_model()


@app.get("/health")
async def health() -> dict:
    payload = {
        "ok": True,
        "engine": ACTIVE_ENGINE,
        "model": MODEL_SIZE,
        "device": RUNTIME_DEVICE,
        "compute_type": RUNTIME_COMPUTE,
    }
    if ACTIVE_ENGINE == "vosk":
        payload["vosk_script"] = VOSK_SCRIPT
    return payload


@app.websocket("/ws")
async def ws_transcribe(ws: WebSocket) -> None:
    if ACTIVE_ENGINE == "vosk":
        await ws_transcribe_vosk(ws)
        return
    await ws_transcribe_whisper(ws)


SILENCE_RMS_THRESHOLD = float(os.getenv("SILENCE_RMS", "0.008"))  # ~-42 dB
SILENCE_CHUNKS_FINAL  = int(os.getenv("SILENCE_CHUNKS", "3"))      # 3 × 200 ms = 600 ms

# Sentence-ending punctuation: commit final immediately on detection
_SENTENCE_END = frozenset("。！？.!?")

# Lower = more aggressive silence filtering (0.0–1.0; default faster-whisper=0.6).
# Note: common hallucinations have high logprob so this alone won't catch them;
# the _HALLUCINATIONS blocklist below is the primary guard.
NO_SPEECH_THRESHOLD = float(os.getenv("NO_SPEECH_THRESHOLD", "0.5"))

# Known Whisper hallucinations to silently discard (exact match after strip)
_HALLUCINATIONS: set[str] = {
    "ご視聴ありがとうございました",
    "ありがとうございました",
    "字幕は自動生成されています",
    "字幕制作",
    "チャンネル登録をお願いします",
    "お疲れ様でした",
    "ご清聴ありがとうございました",
    "モデルの設定",
    "設定",
    "コンプリート",
    "このようなモデルを使用することができます",
    "このようなモデルを使用することができます。",
    "モデルパーティー数分間",
    "このプログラムは、やり方を読んでいただきたいと思います",
    "このプログラムは、やり方を読んでいただきたいと思います。",
    "やり方を読んでいただきたいと思います",
    "おはようございます",
    "おはようございます。",
    "こんにちは",
    "こんにちは。",
    "Thank you for watching.",
    "Thank you for watching",
    "Please subscribe.",
    "Subtitles by",
    "[Music]",
    "[Applause]",
    "[Laughter]",
}


def _is_hallucination(text: str) -> bool:
    t = text.strip().rstrip("。．.")
    return t in _HALLUCINATIONS or text.strip() in _HALLUCINATIONS


def _is_repetitive_loop(text: str) -> bool:
    """Detect Whisper looping: same short phrase repeated many times."""
    if not text:
        return False

    # Check 1: delimiter-based (comma/period-separated segments)
    parts = [p.strip() for p in text.replace("、", ",").replace("。", ",").split(",") if p.strip()]
    if len(parts) >= 4 and len(set(parts)) / len(parts) < 0.3:
        return True

    # Check 2: raw consecutive repetition starting from position 0 (e.g. 大学院大学院…)
    n = len(text)
    for unit_len in range(2, min(14, n // 4 + 1)):
        unit = text[:unit_len]
        count = 0
        pos = 0
        while pos + unit_len <= n and text[pos:pos + unit_len] == unit:
            count += 1
            pos += unit_len
        if count >= 4 and count * unit_len >= n * 0.6:
            return True

    # Check 3: repetition anywhere in the string (e.g. …人間の人間の人間の人間の…)
    if re.search(r'(.{2,10})\1{4,}', text):
        return True

    return False


def _chunk_rms(data: bytes) -> float:
    samples = np.frombuffer(data, dtype=np.int16).astype(np.float32)
    return float(np.sqrt(np.mean(samples ** 2))) / 32768.0


PARTIAL_TIMEOUT   = float(os.getenv("PARTIAL_TIMEOUT",   "3.0"))  # commit if partial unchanged this long
MAX_PARTIAL_AGE   = float(os.getenv("MAX_PARTIAL_AGE",   "5.0"))  # force-commit after this long since first partial


async def ws_transcribe_whisper(ws: WebSocket) -> None:
    _session_started()
    await ws.accept()
    pcm              = bytearray()
    language         = "auto"
    last_sent         = ""
    last_lang         = "ja"
    silent_count      = 0      # consecutive silent 200-ms chunks
    last_sent_time    = 0.0    # when last_sent was last updated
    first_partial_time = 0.0   # when the current partial epoch first started
    stop_event        = asyncio.Event()

    async def transcribe_loop() -> None:
        nonlocal last_sent, last_lang, last_sent_time, first_partial_time
        while not stop_event.is_set():
            await asyncio.sleep(TRANSCRIBE_INTERVAL)
            if len(pcm) // 2 < MIN_SAMPLES:
                continue

            now = asyncio.get_event_loop().time()

            # Commit if partial is unchanged for PARTIAL_TIMEOUT, or has been
            # growing for MAX_PARTIAL_AGE (handles continuous speech where text
            # keeps changing and the unchanged-timeout never fires).
            is_stale = last_sent and (now - last_sent_time) >= PARTIAL_TIMEOUT
            is_old   = first_partial_time > 0 and (now - first_partial_time) >= MAX_PARTIAL_AGE
            if is_stale or is_old:
                await ws.send_text(json.dumps({"type": "final", "text": last_sent, "lang": last_lang}))
                del pcm[:]
                last_sent          = ""
                last_sent_time     = 0.0
                first_partial_time = 0.0
                silent_count       = 0
                continue

            start_byte = max(0, len(pcm) - WINDOW_SAMPLES * 2)
            chunk = bytes(pcm[start_byte:])
            audio = np.frombuffer(chunk, dtype=np.int16).astype(np.float32) / 32768.0
            lang_arg = None if language == "auto" else language

            try:
                segments, info = model.transcribe(
                    audio,
                    language=lang_arg,
                    beam_size=1,
                    best_of=1,
                    vad_filter=VAD_FILTER,
                    condition_on_previous_text=False,
                    without_timestamps=True,
                    temperature=0.0,
                    initial_prompt=INITIAL_PROMPT,
                    no_speech_threshold=NO_SPEECH_THRESHOLD,
                )
            except Exception as exc:
                if RUNTIME_DEVICE == "cuda" and _is_cuda_runtime_error(exc):
                    try:
                        force_cpu_fallback()
                        await ws.send_text(json.dumps({"type": "status", "message": "CUDA libs missing, switched to CPU int8"}))
                        continue
                    except Exception:
                        logger.exception("CPU fallback failed")
                logger.exception("Transcription failed")
                await ws.send_text(json.dumps({"type": "error", "message": f"Transcription error: {exc}"}))
                continue

            text = " ".join(seg.text.strip() for seg in segments).strip()
            if text and text != last_sent and not _is_hallucination(text) and not _is_repetitive_loop(text):
                if not last_sent:
                    first_partial_time = asyncio.get_event_loop().time()
                last_sent      = text
                last_lang      = info.language
                last_sent_time = asyncio.get_event_loop().time()

                # Commit immediately on sentence-ending punctuation
                if len(text) >= 5 and text[-1] in _SENTENCE_END:
                    await ws.send_text(json.dumps({"type": "final", "text": text, "lang": info.language}))
                    del pcm[:]
                    last_sent          = ""
                    last_sent_time     = 0.0
                    first_partial_time = 0.0
                    silent_count       = 0
                else:
                    await ws.send_text(json.dumps({"type": "partial", "text": text, "lang": info.language}))

    task = asyncio.create_task(transcribe_loop())
    await ws.send_text(
        json.dumps(
            {
                "type": "status",
                "message": (
                    f"Remote ready ({MODEL_SIZE}, {RUNTIME_DEVICE}/{RUNTIME_COMPUTE}, "
                    f"vad_filter={VAD_FILTER})"
                ),
            }
        )
    )

    try:
        while True:
            msg = await ws.receive()
            if "bytes" in msg and msg["bytes"] is not None:
                data = msg["bytes"]
                pcm.extend(data)
                cap = WINDOW_SAMPLES * 2 * 4
                if len(pcm) > cap:
                    del pcm[: len(pcm) - cap]

                # Silence detection — emit final when mic goes quiet after speech
                if _chunk_rms(data) < SILENCE_RMS_THRESHOLD:
                    silent_count += 1
                    if silent_count == SILENCE_CHUNKS_FINAL and last_sent:
                        await ws.send_text(json.dumps({"type": "final", "text": last_sent, "lang": last_lang}))
                        del pcm[:]
                        last_sent          = ""
                        last_sent_time     = 0.0
                        first_partial_time = 0.0
                        silent_count       = 0
                else:
                    silent_count = 0

            elif "text" in msg and msg["text"] is not None:
                payload = json.loads(msg["text"])
                ptype = payload.get("type")
                if ptype == "config":
                    selected = payload.get("language", "auto")
                    language = selected if selected in {"auto", "en", "ja"} else "auto"
                    await ws.send_text(json.dumps({"type": "status", "message": f"Language set to {language}"}))
                elif ptype == "stop":
                    break
            elif msg.get("type") == "websocket.disconnect":
                break
    except WebSocketDisconnect:
        pass
    except Exception:
        logger.exception("WebSocket session failed")
    finally:
        # Flush any remaining partial as final
        if last_sent:
            with suppress(Exception):
                await ws.send_text(json.dumps({"type": "final", "text": last_sent, "lang": last_lang}))
        stop_event.set()
        task.cancel()
        with suppress(asyncio.CancelledError):
            await task
        with suppress(Exception):
            await ws.close()
        _session_ended()


async def ws_transcribe_vosk(ws: WebSocket) -> None:
    await ws.accept()
    language = "auto"
    proc: Optional[asyncio.subprocess.Process] = None
    reader_task: Optional[asyncio.Task] = None

    async def start_proc(lang: str) -> tuple[asyncio.subprocess.Process, asyncio.Task]:
        if not os.path.isfile(VOSK_SCRIPT):
            raise FileNotFoundError(f"Vosk stream script not found: {VOSK_SCRIPT}")

        cmd = [
            "python3",
            VOSK_SCRIPT,
            "--sample-rate",
            "16000",
            "--language",
            lang,
        ]
        p = await asyncio.create_subprocess_exec(
            *cmd,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        async def read_stdout() -> None:
            assert p.stdout is not None
            while True:
                line = await p.stdout.readline()
                if not line:
                    break
                raw = line.decode("utf-8", errors="replace").strip()
                if not raw:
                    continue
                try:
                    payload = json.loads(raw)
                except Exception:
                    await ws.send_text(json.dumps({"type": "error", "message": raw}))
                    continue

                ptype = payload.get("type")
                if ptype == "result":
                    await ws.send_text(
                        json.dumps(
                            {
                                "type": "final",
                                "text": payload.get("text", ""),
                                "lang": payload.get("language", lang),
                            }
                        )
                    )
                elif ptype == "partial":
                    await ws.send_text(
                        json.dumps(
                            {
                                "type": "partial",
                                "text": payload.get("text", ""),
                                "lang": payload.get("language", lang),
                            }
                        )
                    )
                else:
                    await ws.send_text(json.dumps(payload))

        return p, asyncio.create_task(read_stdout())

    async def stop_proc() -> None:
        nonlocal proc, reader_task
        if proc is None:
            return

        if proc.stdin is not None:
            with suppress(Exception):
                proc.stdin.close()

        with suppress(Exception):
            await asyncio.wait_for(proc.wait(), timeout=1.5)
        if proc.returncode is None:
            with suppress(Exception):
                proc.terminate()
            with suppress(Exception):
                await asyncio.wait_for(proc.wait(), timeout=1.5)
        if proc.returncode is None:
            with suppress(Exception):
                proc.kill()

        if reader_task is not None:
            reader_task.cancel()
            with suppress(asyncio.CancelledError):
                await reader_task

        proc = None
        reader_task = None

    try:
        proc, reader_task = await start_proc(language)
        await ws.send_text(
            json.dumps(
                {
                    "type": "status",
                    "message": f"Remote ready (vosk, language={language})",
                }
            )
        )

        while True:
            msg = await ws.receive()
            if "bytes" in msg and msg["bytes"] is not None:
                if proc is None or proc.stdin is None:
                    await ws.send_text(json.dumps({"type": "error", "message": "Vosk process not running"}))
                    continue
                proc.stdin.write(msg["bytes"])
                await proc.stdin.drain()
            elif "text" in msg and msg["text"] is not None:
                payload = json.loads(msg["text"])
                ptype = payload.get("type")
                if ptype == "config":
                    selected = payload.get("language", "auto")
                    selected = selected if selected in {"auto", "en", "ja"} else "auto"
                    if selected != language:
                        language = selected
                        await stop_proc()
                        proc, reader_task = await start_proc(language)
                    await ws.send_text(
                        json.dumps(
                            {
                                "type": "status",
                                "message": f"Language set to {language}",
                            }
                        )
                    )
                elif ptype == "stop":
                    break
            elif msg.get("type") == "websocket.disconnect":
                break
    except WebSocketDisconnect:
        pass
    except Exception as exc:
        logger.exception("Vosk websocket session failed")
        with suppress(Exception):
            await ws.send_text(json.dumps({"type": "error", "message": f"Vosk error: {exc}"}))
    finally:
        await stop_proc()
        with suppress(Exception):
            await ws.close()
